In [1]:
import pandas as pd

In [2]:
# reading data from the csv file using pandas
nike_dataframe = pd.read_csv("data/nba.csv", index_col ="Name")

In [5]:
# Displays the list of colum,en from the dataframe
nike_dataframe.columns

Index(['Team', 'Number', 'Position', 'Age', 'Height', 'Weight', 'College',
       'Salary'],
      dtype='object')

In [3]:
nike_dataframe.describe()

Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [8]:
# Verify the stats specific to a series.
nike_dataframe["Position"].describe()

count     457
unique      5
top        SG
freq      102
Name: Position, dtype: object

In [14]:
# Convert the dataframe to numpy array
nike_dataframe_filtered = nike_dataframe[['Age', 'Weight']].head(5)

In [15]:
nike_filterred_array = nike_dataframe_filtered.to_numpy()
print(nike_filterred_array)

[[ 25. 180.]
 [ 25. 235.]
 [ 27. 205.]
 [ 22. 185.]
 [ 29. 231.]]


In [17]:
# Providing the datatype while transforming the array , here we are fioltering the array to avaoid error while transforming.
print(nike_dataframe_filtered.to_numpy(dtype='float32'))

[[ 25. 180.]
 [ 25. 235.]
 [ 27. 205.]
 [ 22. 185.]
 [ 29. 231.]]


In [19]:
# creating series form weight column
weight_series = pd.Series(nike_dataframe_filtered['Weight'].head())
weight_series

Name
Avery Bradley    180.0
Jae Crowder      235.0
John Holland     205.0
R.J. Hunter      185.0
Jonas Jerebko    231.0
Name: Weight, dtype: float64

In [21]:
# Converting the series to numpy data 
conv_array = weight_series.to_numpy()
print(conv_array)

[180. 235. 205. 185. 231.]


In [22]:
# Check the type of the Converted array
print(type(conv_array))

<class 'numpy.ndarray'>


In [23]:
# provide the data type while transforming in to Numpy Arrays 
conv_array = weight_series.to_numpy(dtype ='float32')
print(conv_array)

[180. 235. 205. 185. 231.]
